# Inputs
# - NUM_CHANNELS: Number of channels
# - NUM_STREAMS: Number of streams per channel

macro(generate_ecic
    FILEPATH
    DIRECTION
    NUM_CHANNELS
    NUM_STREAMS
    NUM_SIGNALS
    STREAM_TYPE)

set(CONTENT "<?xml version=\"1.0\" encoding=\"UTF-8\"?>

<!--
The MIT Licence

Copyright (c) 2020 Airbus Operations S.A.S

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the \"Software\"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
-->")

string(APPEND CONTENT "
<ED247ComponentInstanceConfiguration ComponentType=\"Virtual\" Name=\"ComponentGen${DIRECTION}\" Comment=\"Generated by the ED-247 LIBRARY\" StandardRevision=\"A\" Identifier=\"1\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"ED247A_ECIC.xsd\">
	<Channels>")

math(EXPR NUM_CHANNELS "${NUM_CHANNELS}-1")
math(EXPR NUM_STREAMS "${NUM_STREAMS}-1")
math(EXPR NUM_SIGNALS "${NUM_SIGNALS}-1")

foreach(ICHANNEL RANGE ${NUM_CHANNELS})

    math(EXPR PORT "4000+${ICHANNEL}")
    string(APPEND CONTENT "
        <MultiChannel Name=\"C${ICHANNEL}\">
            <FrameFormat StandardRevision=\"A\"/>
            <ComInterface>
                <UDP_Sockets>
                    <UDP_Socket DstIP=\"224.1.1.1\" MulticastInterfaceIP=\"${TEST_MULTICAST_INTERFACE_IP}\" DstPort=\"${PORT}\" Direction=\"${DIRECTION}\"/>
                </UDP_Sockets>
            </ComInterface>
            <Streams>")

    if(${STREAM_TYPE} STREQUAL "A429_Stream")
        foreach(ISTREAM RANGE ${NUM_STREAMS})
            string(APPEND CONTENT "
                <A429_Stream UID=\"${ISTREAM}\" Name=\"C${ICHANNEL}_S${ISTREAM}\" Direction=\"${DIRECTION}\"/>")
        endforeach(ISTREAM RANGE ${NUM_STREAMS})
    endif()

    if(${STREAM_TYPE} STREQUAL "A825_Stream")
        foreach(ISTREAM RANGE ${NUM_STREAMS})
            string(APPEND CONTENT "
                <A825_Stream UID=\"${ISTREAM}\" Name=\"C${ICHANNEL}_S${ISTREAM}\" Direction=\"${DIRECTION}\"/>")
        endforeach(ISTREAM RANGE ${NUM_STREAMS})
    endif()

    if(${STREAM_TYPE} STREQUAL "A664_Stream")
        foreach(ISTREAM RANGE ${NUM_STREAMS})
            string(APPEND CONTENT "
                <A664_Stream UID=\"${ISTREAM}\" Name=\"C${ICHANNEL}_S${ISTREAM}\" Direction=\"${DIRECTION}\"/>")
        endforeach(ISTREAM RANGE ${NUM_STREAMS})
    endif()

    if(${STREAM_TYPE} STREQUAL "DIS_Stream")
        foreach(ISTREAM RANGE ${NUM_STREAMS})
            string(APPEND CONTENT "
                <DIS_Stream UID=\"${ISTREAM}\" Name=\"C${ICHANNEL}_S${ISTREAM}\" Direction=\"${DIRECTION}\">
                    <Signals>")
            foreach(ISIGNAL RANGE ${NUM_SIGNALS})
                math(EXPR BYTEOFFSET "${ISIGNAL}*1")
                string(APPEND CONTENT "
                        <Signal Name=\"C${ICHANNEL}_S${ISTREAM}_S${ISIGNAL}\" ByteOffset=\"${BYTEOFFSET}\"/>")
            endforeach(ISIGNAL RANGE ${NUM_SIGNALS})
            string(APPEND CONTENT "
                    </Signals>
                </DIS_Stream>")
        endforeach(ISTREAM RANGE ${NUM_STREAMS})
    endif()

    if(${STREAM_TYPE} STREQUAL "ANA_Stream")
        foreach(ISTREAM RANGE ${NUM_STREAMS})
            string(APPEND CONTENT "
                <ANA_Stream UID=\"${ISTREAM}\" Name=\"C${ICHANNEL}_S${ISTREAM}\" Direction=\"${DIRECTION}\">
                    <Signals>")
            foreach(ISIGNAL RANGE ${NUM_SIGNALS})
                math(EXPR BYTEOFFSET "${ISIGNAL}*4")
                string(APPEND CONTENT "
                        <Signal Name=\"C${ICHANNEL}_S${ISTREAM}_S${ISIGNAL}\" ByteOffset=\"${BYTEOFFSET}\"/>")
            endforeach(ISIGNAL RANGE ${NUM_SIGNALS})
            string(APPEND CONTENT "
                    </Signals>
                </ANA_Stream>")
        endforeach(ISTREAM RANGE ${NUM_STREAMS})
    endif()

    if(${STREAM_TYPE} STREQUAL "NAD_Stream")
        foreach(ISTREAM RANGE ${NUM_STREAMS})
            string(APPEND CONTENT "
                <NAD_Stream UID=\"${ISTREAM}\" Name=\"C${ICHANNEL}_S${ISTREAM}\" Direction=\"${DIRECTION}\">
                    <Signals>")
            foreach(ISIGNAL RANGE ${NUM_SIGNALS})
                math(EXPR BYTEOFFSET "${ISIGNAL}*4")
                string(APPEND CONTENT "
                        <Signal Name=\"C${ICHANNEL}_S${ISTREAM}_S${ISIGNAL}\" ByteOffset=\"${BYTEOFFSET}\" Type=\"uint32\"/>")
            endforeach(ISIGNAL RANGE ${NUM_SIGNALS})
            string(APPEND CONTENT "
                    </Signals>
                </NAD_Stream>")
        endforeach(ISTREAM RANGE ${NUM_STREAMS})
    endif()

    string(APPEND CONTENT "
            </Streams>
        </MultiChannel>")

endforeach(ICHANNEL RANGE ${NUM_CHANNELS})

string(APPEND CONTENT "    
	</Channels>
</ED247ComponentInstanceConfiguration>
")

message("Write ${FILEPATH}")

file(WRITE ${FILEPATH} ${CONTENT})

endmacro()

